export default {
    Data: [{indexname:'Nifty Pharma',indexid:'13017',exchange:'50',scripcode:'CNXPHARMA'},
    {indexname:'Nifty Growth Sectors 15',indexid:'14353',exchange:'50',scripcode:'NI15'},
    {indexname:'Nifty FMCG',indexid:'13027',exchange:'50',scripcode:'CNXFMCG'},
    {indexname:'Nifty IT',indexid:'186',exchange:'50',scripcode:'CNXIT'},
    {indexname:'Nifty 100 Low Volatility 30',indexid:'15501',exchange:'50',scripcode:'NIF100LW30'},
    {indexname:'Nifty50 Value 20',indexid:'14306',exchange:'50',scripcode:'NV20'},
    {indexname:'Nifty Dividend Opportunities 50',indexid:'13534',exchange:'50',scripcode:'CNXDOI'},
    {indexname:'Nifty India Consumption',indexid:'13653',exchange:'50',scripcode:'CNXCONSUM'},
    {indexname:'NIFTY100 Quality 30',indexid:'15011',exchange:'50',scripcode:'NIFTYQ30'},
    {indexname:'Nifty MNC',indexid:'13019',exchange:'50',scripcode:'CNXMNC'},
    {indexname:'Nifty 50',indexid:'2369',exchange:'50',scripcode:'NSE%20Index'},
    {indexname:'Nifty 100',indexid:'2510',exchange:'50',scripcode:'CNX100'},
    {indexname:'Nifty Services Sector',indexid:'13021',exchange:'50',scripcode:'CNXSSI'},
    {indexname:'Nifty 200',indexid:'13602',exchange:'50',scripcode:'CNX200'},
    {indexname:'Nifty 500',indexid:'2371',exchange:'50',scripcode:'CNX500'},
    {indexname:'Nifty100 Equal Weight',indexid:'14303',exchange:'50',scripcode:'CNX100EWI'},
    {indexname:'Nifty Energy',indexid:'13016',exchange:'50',scripcode:'CNXENERGY'},
    {indexname:'Nifty Financial Services',indexid:'13655',exchange:'50',scripcode:'FINNIFTY'},
    {indexname:'Nifty Infrastructure',indexid:'13022',exchange:'50',scripcode:'CNXINFRA'},
    {indexname:'Nifty Next 50',indexid:'2346',exchange:'50',scripcode:'JUNIOR'},
    {indexname:'Nifty CPSE',indexid:'14214',exchange:'50',scripcode:'CPSE'},
    {indexname:'Nifty Commodities',indexid:'13654',exchange:'50',scripcode:'CNXCOMMO'},
    {indexname:'Nifty 100 Liquid 15',indexid:'13931',exchange:'50',scripcode:'LIX15'},
    {indexname:'Nifty Bank',indexid:'1913',exchange:'50',scripcode:'BANKNIFTY'},
    {indexname:'Nifty Auto',indexid:'13603',exchange:'50',scripcode:'CNXAUTO'},
    {indexname:'Nifty PSE',indexid:'13029',exchange:'50',scripcode:'CNXPSE'},
    {indexname:'Nifty Alpha 50',indexid:'14116',exchange:'50',scripcode:'NIFALPHA50'},
    {indexname:'Nifty Private Bank',indexid:'15270',exchange:'50',scripcode:'NIFTYPBI'},
    {indexname:'Nifty Smallcap 100',indexid:'13532',exchange:'50',scripcode:'CNXSCAP'},
    {indexname:'Nifty Midcap 100',indexid:'2495',exchange:'50',scripcode:'CNXMIDCAP'},
    {indexname:'Nifty Metal',indexid:'13605',exchange:'50',scripcode:'CNXMETAL'},
    {indexname:'Nifty Midcap Liquid 15',indexid:'14967',exchange:'50',scripcode:'NIFTYML15'},
    {indexname:'Nifty Midcap 50',indexid:'2907',exchange:'50',scripcode:'MIDCAP50'},
    {indexname:'Nifty Realty',indexid:'13030',exchange:'50',scripcode:'CNXREALTY'},
    {indexname:'Nifty Media',indexid:'13604',exchange:'50',scripcode:'CNXMEDIA'},
    {indexname:'Nifty PSU Bank',indexid:'13026',exchange:'50',scripcode:'CNXPSUBANK'},
    {indexname:'S&P BSE Sensex',indexid:'2365',exchange:'47',scripcode:'Sensex'},
    {indexname:'S&P BSE SENSEX Next 50',indexid:'15817',exchange:'47',scripcode:'SNXT50'},
    {indexname:'S&P BSE Bankex',indexid:'2647',exchange:'47',scripcode:'Bankex'},
    {indexname:'S&P BSE Consumer Durables',indexid:'2275',exchange:'47',scripcode:'BSE%20CD'},
    {indexname:'S&P BSE Infotech',indexid:'2157',exchange:'47',scripcode:'BSE%20IT'},
    {indexname:'S&P BSE Healthcare',indexid:'2276',exchange:'47',scripcode:'BSE%20HC'},
    {indexname:'S&P BSE Auto Index',indexid:'2416',exchange:'47',scripcode:'BSEAUT'},
    {indexname:'S&P BSE Small-Cap',indexid:'2022',exchange:'47',scripcode:'BSESC'},
    {indexname:'S&P BSE Capital Goods',indexid:'2273',exchange:'47',scripcode:'BSECAP'},
    {indexname:'S&P BSE Mid-Cap',indexid:'1906',exchange:'47',scripcode:'BSEMC'},
    {indexname:'S&P BSE 500',indexid:'2342',exchange:'47',scripcode:'BSE500'},
    {indexname:'S&P BSE Metal Index',indexid:'2449',exchange:'47',scripcode:'BSEMET'},
    {indexname:'S&P BSE Sensex 50',indexid:'15648',exchange:'47',scripcode:'SNSX50'},
    {indexname:'S&P BSE 100',indexid:'2340',exchange:'47',scripcode:'BSENAT'},
    {indexname:'S&P BSE Oil & Gas Index',indexid:'2555',exchange:'47',scripcode:'BSEOIL'},
    {indexname:'S&P BSE FMCG',indexid:'2274',exchange:'47',scripcode:'BSEFMC'},
    {indexname:'S&P BSE TECk Index',indexid:'10968',exchange:'47',scripcode:'BSETEC'},
    {indexname:'S&P BSE IPO Index',indexid:'12725',exchange:'47',scripcode:'BSEIPO'},
    {indexname:'S&P BSE MidCap Select Index',indexid:'14958',exchange:'47',scripcode:'BMCSI'},
    {indexname:'S&P BSE Finance',indexid:'14918',exchange:'47',scripcode:'BFIN'},
    {indexname:'S&P BSE 150 MidCap Index',indexid:'16178',exchange:'47',scripcode:'MID150'},
    {indexname:'S&P BSE Public Sector',indexid:'6929',exchange:'47',scripcode:'BSEPUB'},
    {indexname:'S&P BSE 200',indexid:'2364',exchange:'47',scripcode:'BSE200'},
    {indexname:'S&P BSE Energy',indexid:'14911',exchange:'47',scripcode:'Energy'},
    {indexname:'S&P BSE 250 LargeMidCap Index',indexid:'16181',exchange:'47',scripcode:'LMI250'},
    {indexname:'S&P BSE LargeCap',indexid:'14852',exchange:'47',scripcode:'BLC'},
    {indexname:'S&P BSE AllCap',indexid:'14912',exchange:'47',scripcode:'ALLCAP'},
    {indexname:'S&P BSE Dollex - 30',indexid:'9999',exchange:'47',scripcode:'DOL30'},
    {indexname:'S&P BSE 400 MidSmallCap Index',indexid:'16177',exchange:'47',scripcode:'MSL400'},
    {indexname:'S&P BSE Consumer Discretionary Goods & Services',indexid:'14857',exchange:'47',scripcode:'CDGS'},
    {indexname:'S&P BSE Basic Materials',indexid:'14849',exchange:'47',scripcode:'BBM'},
    {indexname:'S&P BSE Industrials',indexid:'14856',exchange:'47',scripcode:'INDUS'},
    {indexname:'S&P BSE Greenex',indexid:'13658',exchange:'47',scripcode:'BSEGR'},
    {indexname:'S&P BSE SmallCap Select Index',indexid:'14959',exchange:'47',scripcode:'BSCSI'},
    {indexname:'S&P BSE Bharat 22 Index',indexid:'16021',exchange:'47',scripcode:'BHRT22'},
    {indexname:'S&P BSE 250 SmallCap Index',indexid:'16179',exchange:'47',scripcode:'SML250'},
    {indexname:'S&P BSE Realty Index',indexid:'2739',exchange:'47',scripcode:'BSEREA'},
    {indexname:'S&P BSE Power Index',indexid:'12356',exchange:'47',scripcode:'BSEPOW'},
    {indexname:'S&P BSE Carbonex',indexid:'13792',exchange:'47',scripcode:'CARBON'},
    {indexname:'S&P BSE Utilities',indexid:'14848',exchange:'47',scripcode:'BSEUT'},
    {indexname:'S&P BSE Dollex - 100',indexid:'2090',exchange:'47',scripcode:'DOL100'},
    {indexname:'S&P BSE SME IPO',indexid:'13794',exchange:'47',scripcode:'SMEIPO'},
    {indexname:'S&P BSE Dollex - 200',indexid:'2341',exchange:'47',scripcode:'DOLLEX'},
    {indexname:'S&P BSE Telecom',indexid:'14917',exchange:'47',scripcode:'BSETC'},
    {indexname:'S&P BSE TASIS Shariah 50',indexid:'13393',exchange:'47',scripcode:'SHA50'},
    {indexname:'S&P BSE CPSE',indexid:'14537',exchange:'47',scripcode:'CPSE'},
    {indexname:'S&P BSE Momentum',indexid:'16211',exchange:'47',scripcode:'BSEMOI'},
    {indexname:'S&P BSE India Manufacturing Index',indexid:'14854',exchange:'47',scripcode:'MFG'},
    {indexname:'S&P BSE Dividend Stability Index',indexid:'14968',exchange:'47',scripcode:'BSEDSI'},
    {indexname:'S&P BSE Enhanced Value',indexid:'16212',exchange:'47',scripcode:'BSEEVI'},
    {indexname:'S&P BSE 100 ESG Index',indexid:'16136',exchange:'47',scripcode:'ESG100'},
    {indexname:'S&P BSE India Infrastructure Index',indexid:'14354',exchange:'47',scripcode:'INFRA'},   ]
}