export default {
    Data: [{companyid:'12934',name:'TATAMDVR'},
    {companyid:'13938',name:'Bliss GVS Pharma'},
    {companyid:'31253',name:'CREACCGRAM'},
    {companyid:'17141',name:'BAG Films & Media'},
    {companyid:'13280',name:'Marathon'},
    {companyid:'7750',name:'RBLBANK'},
    {companyid:'15580',name:'Indiabulls Housing Finance Ltd'},
    {companyid:'12393',name:'DLF'},
    {companyid:'9196',name:'IndusInd Bank'},
    {companyid:'11260',name:'Bajaj Finance'},
    {companyid:'4940',name:'DCB Bank Ltd'},
    {companyid:'16320',name:'PVR'},
    {companyid:'66383',name:'Ujjivan Small Finance Bank'},
    {companyid:'33652',name:'Lemon Tree'},
    {companyid:'42269',name:'PC Jeweller'},
    {companyid:'21608',name:'Ashoka Buildcon'},
    {companyid:'12713',name:'Amara Raja Batteries'},
    {companyid:'66320',name:'Shrenik'},
    {companyid:'30990',name:'Hathway Cable & Datacom'},
    {companyid:'30425',name:'Den Networks'},
    {companyid:'13826',name:'EIH'},
    {companyid:'13636',name:'Hero MotoCorp'},
    {companyid:'32209',name:'Ujjivan Financial Services Limited'},
    {companyid:'13974',name:'Bata India'},
    {companyid:'1886',name:'Inox Leisure'},
    {companyid:'11699',name:'ITI'},
    {companyid:'12830',name:'VIP Industries'},
    {companyid:'3296',name:'Sunteck Realty'},
    {companyid:'1850838',name:'Chalet Hotels'},
    {companyid:'3837',name:'Westlife Development'},
    {companyid:'5038',name:'Jindal Worldwide'},
    {companyid:'16016',name:'Nitco'},
    {companyid:'46514',name:'SIS LIMITED'},
    {companyid:'53568',name:'Apollo Micro'},
    {companyid:'12132',name:'NESCO'},
    {companyid:'37726',name:'MT Educare'},
    {companyid:'13259',name:'PTL Enterprises'},
    {companyid:'19365',name:'Shivam Autotech'},
    {companyid:'13483',name:'Whirlpool of India'},
    {companyid:'20507',name:'PPAP Automotive Ltd'},
    {companyid:'18559',name:'Cineline India Ltd'},
    {companyid:'9036',name:'Liberty Shoes'},
    {companyid:'65982',name:'PSPPROJECT'},
    {companyid:'12866',name:'Uniphos Enterprises'},
    {companyid:'5947',name:'Paisalo Digital'},
    {companyid:'14011',name:'Force Motors'},
    {companyid:'8313',name:'IMP Powers'},
    {companyid:'10860',name:'Mazda'},
    {companyid:'62853',name:'Prataap Snacks'},
    {companyid:'10512',name:'Crest Ventures Ltd'},
    {companyid:'13655',name:'The Hi-Tech Gears'},
    {companyid:'12061',name:'India Motor Parts and Accessories'},
    {companyid:'3154',name:'Vodafone Idea'},
    {companyid:'11585',name:'Punjab National Bank'},
    {companyid:'12918',name:'Tata Power Company'},
    {companyid:'16552',name:'Yes Bank'},
    {companyid:'11974',name:'Steel Authority of India'},
    {companyid:'11831',name:'Bharat Heavy Electricals'},
    {companyid:'62245',name:'IDFCBANK'},
    {companyid:'12040',name:'Bank of Baroda'},
    {companyid:'11984',name:'State Bank of India'},
    {companyid:'11713',name:'Indian Overseas Bank'},
    {companyid:'4422',name:'Reliance Power'},
    {companyid:'1513',name:'Jaiprakash Power Ventures'},
    {companyid:'4325',name:'Subex'},
    {companyid:'14041',name:'Ashok Leyland'},
    {companyid:'13554',name:'ITC'},
    {companyid:'9211',name:'Federal Bank'},
    {companyid:'30050',name:'L&T Finance Holdings'},
    {companyid:'20316',name:'Adani Ports & Special Economic Zone'},
    {companyid:'9218',name:'Canara Bank'},
    {companyid:'12283',name:'Bank of Maharashtra'},
    {companyid:'11997',name:'National Aluminium Company'},
    {companyid:'11599',name:'Oil & Natural Gas Corporation'},
    {companyid:'3778',name:'Cadila Healthcare'},
    {companyid:'9194',name:'ICICI Bank'},
    {companyid:'1428',name:'GMR Infrastructure'},
    {companyid:'11769',name:'Zee Entertainment'},
    {companyid:'1209',name:'Suzlon Energy'},
    {companyid:'19818',name:'JSW Energy'},
    {companyid:'12902',name:'Tata Steel'},
    {companyid:'11689',name:'IDBI Bank'},
    {companyid:'4531',name:'NBCC (India)'},
    {companyid:'10960',name:'Infosys'},
    {companyid:'12316',name:'NTPC'},
    {companyid:'11924',name:'Indian Oil Corporation'},
    {companyid:'3540',name:'Mahindra & Mahindra Financial'},
    {companyid:'12249',name:'South Indian Bank'},
    {companyid:'11944',name:'Central Bank of India'},
    {companyid:'11265',name:'SREI Infrastructure Finance'},
    {companyid:'13637',name:'Hindalco Industries'},
    {companyid:'4845',name:'GAIL (India)'},
    {companyid:'23479',name:'Adani Power'},
    {companyid:'9134',name:'Sun Pharmaceutical Industries'},
    {companyid:'12799',name:'Wipro'},
    {companyid:'11163',name:'Trident'},
    {companyid:'13111',name:'VEDL'},
    {companyid:'9175',name:'Axis Bank'},
    {companyid:'11964',name:'Bank of India'},
    {companyid:'10648',name:'Alok Industries'},
    {companyid:'10434',name:'Tata Steel BSL'},
    {companyid:'1481',name:'Jaiprakash Associates'},
    {companyid:'9074',name:'Adani Enterprises'},
    {companyid:'10878',name:'Motherson Sumi Systems'},
    {companyid:'4519',name:'Power Finance Corporation'},
    {companyid:'12261',name:'Union Bank of India'},
    {companyid:'11215',name:'Morepen Laboratories'},
    {companyid:'15279',name:'Reliance Communications'},
    {companyid:'4355',name:'Jindal Steel & Power'},
    {companyid:'11945',name:'Bharat Electronics'},
    {companyid:'11633',name:'NMDC Ltd'},
    {companyid:'11822',name:'Coal India'},
    {companyid:'9195',name:'HDFC Bank'},
    {companyid:'9180',name:'UCO Bank'},
    {companyid:'4436',name:'IDFC'},
    {companyid:'19231',name:'Indiabulls Real Estate'},
    {companyid:'13643',name:'Ambuja Cements'},
    {companyid:'67665',name:'Bandhan Bank'},
    {companyid:'4628',name:'Power Grid Corporation of India'},
    {companyid:'2718',name:'Bharti Airtel'},
    {companyid:'13215',name:'Reliance Industries'},
    {companyid:'3491',name:'3i Infotech'},
    {companyid:'4616',name:'REC'},
    {companyid:'11088',name:'Himadri Speciality Chem'},
    {companyid:'15481',name:'TV18 Broadcast'},
    {companyid:'11221',name:'Tech Mahindra'},
    {companyid:'18466',name:'Rail Vikas Nigam'},
    {companyid:'16883',name:'GTL Infrastructure'},
    {companyid:'10823',name:'LIC Housing Finance'},
    {companyid:'7134',name:'MANAPPURAM'},
    {companyid:'11234',name:'NCC'},
    {companyid:'12078',name:'HPCL'},
    {companyid:'16648',name:'Fortis Healthcare'},
    {companyid:'13690',name:'Gujarat Alkalies & Chemicals'},
    {companyid:'18608',name:'Shree Renuka Sugars'},
    {companyid:'63',name:'Apollo Tyres'},
    {companyid:'11941',name:'Bharat Petroleum Corporation'},
    {companyid:'12913',name:'Tata Chemicals'},
    {companyid:'20201',name:'Dish TV India'},
    {companyid:'4291',name:'HCL Technologies'},
    {companyid:'6114',name:'UPL Ltd'},
    {companyid:'12159',name:'Cholamandalam Investment & Finance'},
    {companyid:'13998',name:'BAJAJHIND'},
    {companyid:'13649',name:'HFCL Ltd'},
    {companyid:'13922',name:'Reliance Infrastructure'},
    {companyid:'99',name:'Firstsource Solutions'},
    {companyid:'13252',name:'Rain Industries Ltd'},
    {companyid:'4495',name:'Petronet LNG'},
    {companyid:'33818',name:'Future Consumer'},
    {companyid:'35540',name:'VIKASMCORP'},
    {companyid:'18878',name:'Siti Networks'},
    {companyid:'4255',name:'Glenmark Pharmaceuticals'},
    {companyid:'13106',name:'Shriram Transport Finance'},
    {companyid:'66696',name:'Aditya Birla Capital Ltd'},
    {companyid:'18545',name:'LT Foods'},
    {companyid:'8614',name:'Indian Bank'},
    {companyid:'11898',name:'Mahindra & Mahindra'},
    {companyid:'13550',name:'India Cements'},
    {companyid:'16160',name:'Meghmani Organics'},
    {companyid:'11733',name:'Hindustan Copper'},
    {companyid:'11948',name:'Rashtriya Chemicals & Fertilizers'},
    {companyid:'13870',name:'DCW'},
    {companyid:'12929',name:'TATA CONSUMER PRODUCTS'},
    {companyid:'6991',name:'Granules India'},
    {companyid:'11972',name:'Shipping Corporation of India'},
    {companyid:'10501',name:'Vakrangee Ltd'},
    {companyid:'7876',name:'SpiceJet'},
    {companyid:'13916',name:'Graphite India'},
    {companyid:'5032',name:'Welspun Corp'},
    {companyid:'4516',name:'HUDCO'},
    {companyid:'10743',name:'Lupin'},
    {companyid:'14852',name:'Dhani Services'},
    {companyid:'8345',name:'Tata Consultancy'},
    {companyid:'13640',name:'HDFC'},
    {companyid:'13447',name:'Larsen & Toubro'},
    {companyid:'10542',name:'Marksans Pharma'},
    {companyid:'2082',name:'Biocon'},
    {companyid:'7749',name:'City Union Bank'},
    {companyid:'10710',name:'Bodal Chemicals'},
    {companyid:'9453',name:'Delta Corp'},
    {companyid:'12536',name:'NHPC'},
    {companyid:'3068',name:'HDFC LIFE INSURANCE'},
    {companyid:'13269',name:'Prakash Industries'},
    {companyid:'12161',name:'Kotak Mahindra Bank'},
    {companyid:'12477',name:'Balrampur Chini Mills'},
    {companyid:'65921',name:'SINTEXPLAST'},
    {companyid:'13895',name:'Exide Industries'},
    {companyid:'13654',name:'Hindustan Construction Company'},
    {companyid:'8221',name:'Suven Life Sciences'},
    {companyid:'2120',name:'Brightcom Group'},
    {companyid:'11645',name:'MMTC'},
    {companyid:'46091',name:'Aditya Birla Fashion & Retail'},
    {companyid:'32503',name:'Adani Total Gas'},
    {companyid:'41914',name:'SNOWMAN'},
    {companyid:'8279',name:'Aurobindo Pharma'},
    {companyid:'17994',name:'Sun TV Network'},
    {companyid:'12259',name:'Karnataka Bank'},
    {companyid:'45395',name:'Future Retail'},
    {companyid:'11632',name:'National Fertilizer'},
    {companyid:'64057',name:'Infibeam Avenues'},
    {companyid:'16705',name:'Indian Raily Catering And Tourism'},
    {companyid:'12833',name:'Usha Martin'},
    {companyid:'1944712',name:'Sterling And Wilson Solar'},
    {companyid:'751',name:'Indraprastha Gas'},
    {companyid:'12669',name:'Nava Bharat Ventures'},
    {companyid:'2118',name:'Strides Pharma Science'},
    {companyid:'8611',name:'J & K Bank'},
    {companyid:'4582',name:'Engineers India'},
    {companyid:'21826',name:'SBI Cards and Payment Services'},
    {companyid:'12815',name:'Voltas'},
    {companyid:'11980',name:'Ircon International'},
    {companyid:'12096',name:'Welspun India'},
    {companyid:'12937',name:'Tamilnadu Petro Products'},
    {companyid:'4447',name:'Centrum Capital'},
    {companyid:'12462',name:'Mahanagar Telephone Nigam'},
    {companyid:'10378',name:'Praj Industries'},
    {companyid:'66288',name:'AU Small Finance Bank'},
    {companyid:'11582',name:'Punjab & Sind Bank'},
    {companyid:'13616',name:'Hindustan Unilever'},
    {companyid:'20870',name:'Indian Energy'},
    {companyid:'3145',name:'PTC India'},
    {companyid:'67489',name:'ASTDMHEACAR'},
    {companyid:'1714',name:'United Spirits'},
    {companyid:'22411',name:'Indus Towers'},
    {companyid:'18603',name:'Take Solutions'},
    {companyid:'13879',name:'Tata Coffee'},
    {companyid:'13811',name:'Electrosteel Castings'},
    {companyid:'1908',name:'Godrej Consumer Products'},
    {companyid:'7115',name:'Sanghi Industries'},
    {companyid:'11796',name:'Dabur India'},
    {companyid:'4270',name:'Vikas Proppant & Granite'},
    {companyid:'12663',name:'Rolta India'},
    {companyid:'45529',name:'Just Dial'},
    {companyid:'44332',name:'Equitas Holding'},
    {companyid:'11392',name:'Manali Petrochemicals'},
    {companyid:'7528',name:'Vikas Ecotech'},
    {companyid:'3635',name:'Divis Laboratories'},
    {companyid:'13586',name:'Indian Hotels Company'},
    {companyid:'20445',name:'Brigade Enterprises'},
    {companyid:'1898',name:'ICICIPRULI'},
    {companyid:'12903',name:'Titan Company Ltd'},
    {companyid:'4764',name:'Container Corporation of India'},
    {companyid:'15673',name:'Mindtree'},
    {companyid:'61335',name:'CROMPTON'},
    {companyid:'14037',name:'Arvind'},
    {companyid:'750',name:'Jindal Stainless'},
    {companyid:'13866',name:'CG Power & Industrial Solutions'},
    {companyid:'20026',name:'Religare Enterprises'},
    {companyid:'12258',name:'Karur Vysya Bank'},
    {companyid:'18460',name:'SJVN'},
    {companyid:'3589',name:'Dwarikesh Sugar Industries'},
    {companyid:'4653',name:'Gujarat Mineral Dvpt Corporation'},
    {companyid:'13993',name:'Bhansali Engineering Polymers'},
    {companyid:'24320',name:'RTNPOWER'},
    {companyid:'11982',name:'Hindustan Zinc'},
    {companyid:'13532',name:'Jain Irrigation Systems'},
    {companyid:'6947',name:'Jump Networks'},
    {companyid:'11391',name:'MRPL'},
    {companyid:'13958',name:'Bharat Forge'},
    {companyid:'17767',name:'Jagran Prakashan'},
    {companyid:'13577',name:'Castrol India'},
    {companyid:'2898',name:'SBI Life'},
    {companyid:'10507',name:'Havells India'},
    {companyid:'5886',name:'Marico'},
    {companyid:'19129',name:'Time Technoplast'},
    {companyid:'12317',name:'NLC India'},
    {companyid:'18879',name:'Zee Media Corporation Ltd'},
    {companyid:'13678',name:'G S F C'},
    {companyid:'13931',name:'Bombay Dyeing & Manufacturing'},
    {companyid:'13698',name:'Greaves Cotton'},
    {companyid:'4294',name:'Gati'},
    {companyid:'14034',name:'Asian Paints'},
    {companyid:'41253',name:'Orient Cement Ltd'},
    {companyid:'13332',name:'Piramal Enterprises'},
    {companyid:'33218',name:'Muthoot Finance'},
    {companyid:'11784',name:'FDC'},
    {companyid:'10678',name:'Filatex India'},
    {companyid:'59030',name:'GUJGASLTD'},
    {companyid:'60145',name:'Interglobe Aviation'},
    {companyid:'12964',name:'Sunflag Iron'},
    {companyid:'13696',name:'Grasim Industries'},
    {companyid:'12633',name:'JM Financial'},
    {companyid:'12569',name:'Sical Logistics'},
    {companyid:'13149',name:'Jindal Saw'},
    {companyid:'8970',name:'Dhanlaxmi Bank'},
    {companyid:'19509',name:'PTC India Financial Services'},
    {companyid:'4471',name:'BIRLASOFT'},
    {companyid:'13474',name:'Kesoram Industries'},
    {companyid:'45605',name:'Parag Milk'},
    {companyid:'7212',name:'IOL Chemicals and Pharmaceuticals'},
    {companyid:'69000',name:'KPIT Technologies'},
    {companyid:'2101',name:'Gujarat State Petronet'},
    {companyid:'12024',name:'Dewan Housing Finance Corporation'},
    {companyid:'20738',name:'IRB Infrastructure Developers'},
    {companyid:'11827',name:'JK Paper'},
    {companyid:'22426',name:'Jaypee Infratech'},
    {companyid:'13537',name:'J K Tyre & Industries'},
    {companyid:'61755',name:'JSLHISAR'},
    {companyid:'31863',name:'Bajaj Consumer'},
    {companyid:'21076',name:'Titagarh Wagons'},
    {companyid:'3731',name:'Wockhardt'},
    {companyid:'13276',name:'Phillips Carbon'},
    {companyid:'13547',name:'Jamna Auto Inds'},
    {companyid:'66903',name:'SOLARA'},
    {companyid:'31',name:'Alembic'},
    {companyid:'13761',name:'Escorts'},
    {companyid:'12940',name:'TVS Motor Company'},
    {companyid:'8597',name:'Jai Corp'},
    {companyid:'13787',name:'Eicher Motors'},
    {companyid:'18315',name:'Sun Pharma Advanced Research'},
    {companyid:'10661',name:'Rana Sugars'},
    {companyid:'5733',name:'Godrej Properties'},
    {companyid:'10625',name:'IFCI'},
    {companyid:'11890',name:'Maruti Suzuki'},
    {companyid:'3782',name:'Sequent Scientific'},
    {companyid:'13319',name:'Orient Paper & Industries'},
    {companyid:'20724',name:'OnMobile Global'},
    {companyid:'4259',name:'Central Depository Services (India)'},
    {companyid:'62',name:'Apollo Hospitals Enterprises'},
    {companyid:'5449',name:'NAM-INDIA'},
    {companyid:'11992',name:'Tata Communications'},
    {companyid:'13464',name:'Kothari Sugars & Chemicals'},
    {companyid:'13456',name:'Trent'},
    {companyid:'13189',name:'Reliance Capital'},
    {companyid:'8935',name:'Hikal'},
    {companyid:'1883',name:'ICICIGI'},
    {companyid:'13103',name:'Shree Digvijay Cement Co'},
    {companyid:'13325',name:'NOCIL'},
    {companyid:'19100',name:'Edelweiss Financial Services'},
    {companyid:'8492',name:'Torrent Pharmaceuticals'},
    {companyid:'696',name:'Gammon Infrastructure Projects'},
    {companyid:'18352',name:'Info Edge (India)'},
    {companyid:'1367',name:'United Breweries'},
    {companyid:'4285',name:'New Indian Assurance'},
    {companyid:'18767',name:'Torrent Power'},
    {companyid:'32769',name:'Zee Learn'},
    {companyid:'13673',name:'Gujarat Narmada Valley Fertilizers '},
    {companyid:'13763',name:'Gabriel India'},
    {companyid:'13838',name:'Deepak Nitrite'},
    {companyid:'15747',name:'Network 18 Fincap'},
    {companyid:'6',name:'ACC'},
    {companyid:'13928',name:'BOROSIL RENEWABLES'},
    {companyid:'39503',name:'S H Kelkar and Company'},
    {companyid:'14013',name:'Balkrishna Industries'},
    {companyid:'53509',name:'PRICOL'},
    {companyid:'3370',name:'Sterlite Technologies'},
    {companyid:'4264',name:'V-Guard Industries'},
    {companyid:'4301',name:'Triveni Engineering & Industries'},
    {companyid:'13796',name:'Ester Industries'},
    {companyid:'4547',name:'Oil India'},
    {companyid:'33061',name:'A2ZINFRA'},
    {companyid:'3559',name:'Aksh Optifibre'},
    {companyid:'57942',name:'RELHOME'},
    {companyid:'20802',name:'GSS Infotech'},
    {companyid:'4331',name:'Mahanagar Gas'},
    {companyid:'8227',name:'Confidence Petroleum India'},
    {companyid:'1944330',name:'Greenpanel Industries'},
    {companyid:'10460',name:'Pidilite Industries'},
    {companyid:'21430',name:'Bajaj Auto'},
    {companyid:'10801',name:'Aarti Drugs'},
    {companyid:'12266',name:'General Insurance'},
    {companyid:'37311',name:'Schneider Electric Infrastructure'},
    {companyid:'16819',name:'Nectar Lifesciences'},
    {companyid:'5265',name:'ICICI Securities'},
    {companyid:'17871',name:'Sadbhav Engineering'},
    {companyid:'32984',name:'Texmaco Rail & Engineering'},
    {companyid:'13214',name:'Raymond'},
    {companyid:'13861',name:'Can Fin Homes'},
    {companyid:'858',name:'Coforge'},
    {companyid:'11357',name:'Man Industries (India)'},
    {companyid:'33124',name:'Shekhawati Poly-Yarn'},
    {companyid:'12828',name:'Jubilant Pharmova'},
    {companyid:'13911',name:'CESC'},
    {companyid:'13382',name:'Mukand'},
    {companyid:'11661',name:'Chennai Petroleum Corporation'},
    {companyid:'13971',name:'Berger Paints India'},
    {companyid:'52',name:'Andhra Cements'},
    {companyid:'12927',name:'Tinplate Company of India'},
    {companyid:'13837',name:'Deepak Fertilizers & Petrochemicals'},
    {companyid:'21505',name:'RPG Life Sciences'},
    {companyid:'13630',name:'HEG'},
    {companyid:'15274',name:'KNR Constructions'},
    {companyid:'8684',name:'MPhasis'},
    {companyid:'22649',name:'Man Infraconstruction'},
    {companyid:'4156',name:'PNB Gilts'},
    {companyid:'18530',name:'Gayatri Projects'},
    {companyid:'16224',name:'Jubilant Foodworks'},
    {companyid:'12278',name:'CSB Bank'},
    {companyid:'22179',name:'DCAL'},
    {companyid:'13471',name:'Cummins India'},
    {companyid:'13905',name:'Century Textiles & Industries'},
    {companyid:'12675',name:'Balmer Lawrie & Company'},
    {companyid:'4443',name:'Patel Engineering'},
    {companyid:'12807',name:'Walchandnagar Industries'},
    {companyid:'3027',name:'UltraTech Cement'},
    {companyid:'22223',name:'IIFL Securities'},
    {companyid:'10506',name:'HCL Infosystems'},
    {companyid:'30624',name:'MINDACORP'},
    {companyid:'21426',name:'Bajaj Finserv'},
    {companyid:'10952',name:'NIIT'},
    {companyid:'13154',name:'Southern Petrochemicals Industries'},
    {companyid:'10521',name:'Indbank Merchant Banking Services'},
    {companyid:'13205',name:'Rico Auto Industries'},
    {companyid:'20188',name:'VA Tech Wabag'},
    {companyid:'12111',name:'HBL Power Systems'},
    {companyid:'13420',name:'Mangalore Chemicals & Fertilizers'},
    {companyid:'12207',name:'Tata Elxsi'},
    {companyid:'11248',name:'SPML Infra'},
    {companyid:'33621',name:'PNC Infratech'},
    {companyid:'10347',name:'Vikas Wsp'},
    {companyid:'3728',name:'Cerebra Integrrated Technologies'},
    {companyid:'12989',name:'JK Lakshmi Cement'},
    {companyid:'13902',name:'ITD Cementation India'},
    {companyid:'1744',name:'Compuage Infocom'},
    {companyid:'12897',name:'Thomas Cook (India)'},
    {companyid:'47146',name:'Prince Pipes and Fittings'},
    {companyid:'18606',name:'Alpa Laboratories'},
    {companyid:'13435',name:'Max Financial Serv'},
    {companyid:'12883',name:'Eveready Industries India'},
    {companyid:'35834',name:'AAVAS'},
    {companyid:'4501',name:'MOIL'},
    {companyid:'10777',name:'Chambal Fertilisers & Chemicals'},
    {companyid:'4499',name:'Mishra Dhatu Nigam'},
    {companyid:'13802',name:'Elecon Engineering Company'},
    {companyid:'11995',name:'Fertilizers & Chemicals Tranvancore'},
    {companyid:'66440',name:'ORIENTELEC'},
    {companyid:'11377',name:'The Ramco Cements Ltd'},
    {companyid:'12896',name:'Thirumalai Chemicals'},
    {companyid:'8255',name:'Prism Johnson'},
    {companyid:'18643',name:'Everest Kanto Cylinder'},
    {companyid:'61354',name:'NAVKARCORP'},
    {companyid:'7603',name:'KRBL'},
    {companyid:'62089',name:'MAXVIL'},
    {companyid:'16230',name:'Gujarat Pipavav Port'},
    {companyid:'13511',name:'K C P'},
    {companyid:'45987',name:'Avenue Supermarts'},
    {companyid:'12130',name:'Anant Raj'},
    {companyid:'19654',name:'Asian Granito India'},
    {companyid:'4663',name:'MSTC'},
    {companyid:'1844252',name:'Birla Tyres'},
    {companyid:'67250',name:'Shably Ltd'},
    {companyid:'34421',name:'Alembic Pharmaceuticals'},
    {companyid:'49672',name:'Sumitomo Chemical'},
    {companyid:'4809',name:'Greenply Industries'},
    {companyid:'11975',name:'BEML'},
    {companyid:'57724',name:'Adani Transmissions'},
    {companyid:'64987',name:'L&T Technology'},
    {companyid:'12604',name:'Hindustan Oil Exploration Company'},
    {companyid:'17664',name:'Action Construction Equipment'},
    {companyid:'15059',name:'Alkem Laboratories'},
    {companyid:'12782',name:'Dhampur Sugar Mills'},
    {companyid:'34738',name:'Orient Refractories'},
    {companyid:'43060',name:'PRECAM'},
    {companyid:'58859',name:'INTELLECT'},
    {companyid:'51493',name:'B.C. Power Controls'},
    {companyid:'7916',name:'Genus Power Infrastructures'},
    {companyid:'10674',name:'Ashapura Minechem'},
    {companyid:'8336',name:'Kellton Tech Solutions'},
    {companyid:'7374',name:'JMC Projects (India)'},
    {companyid:'18605',name:'VBL'},
    {companyid:'4494',name:'Dolat Investments'},
    {companyid:'5619',name:'Emami'},
    {companyid:'6853',name:'Geojit Financial Serv'},
    {companyid:'16054',name:'KEC International'},
    {companyid:'50029',name:'Music Broadcast'},
    {companyid:'33820',name:'POLYCABINDIA'},
    {companyid:'1090',name:'S.A.L Steel'},
    {companyid:'15743',name:'Oriental Trimex'},
    {companyid:'12898',name:'Tilaknagar Industries'},
    {companyid:'10752',name:'Tata Metaliks'},
    {companyid:'303',name:'Syngene International'},
    {companyid:'13204',name:'Rallis India'},
    {companyid:'18388',name:'STARCEMENT'},
    {companyid:'11077',name:'Kopran'},
    {companyid:'13873',name:'Colgate Palmolive (India)'},
    {companyid:'2809',name:'BSE'},
    {companyid:'65528',name:'Madhav Copper'},
    {companyid:'6724',name:'Avanti Feeds'},
    {companyid:'13277',name:'Surya Roshni'},
    {companyid:'1960165',name:'Suven Pharmaceuticals'},
    {companyid:'7974',name:'Shilpa Medicare'},
    {companyid:'11491',name:'Tamil Nadu Newsprint & Papers'},
    {companyid:'34547',name:'Manaksia Coated Metals & Inds'},
    {companyid:'4558',name:'Sonata Software'},
    {companyid:'11400',name:'Aarti Industries'},
    {companyid:'13284',name:'Pennar Industries'},
    {companyid:'5015',name:'Indraprastha Medical Corporation'},
    {companyid:'61461',name:'Dixon Technologies'},
    {companyid:'18931',name:'CAMLINFINE'},
    {companyid:'5351',name:'Tanla Platforms'},
    {companyid:'13818',name:'EID Parry'},
    {companyid:'10357',name:'PI Industrial'},
    {companyid:'1237',name:'Allied Digital Services'},
    {companyid:'8228',name:'Panama Petrochem'},
    {companyid:'38215',name:'Endurance Techno'},
    {companyid:'19352',name:'SOBHA'},
    {companyid:'13102',name:'Siemens'},
    {companyid:'13357',name:'NCL Industries'},
    {companyid:'7735',name:'GOODLUCK'},
    {companyid:'5485',name:'Cybertech Systems & Software'},
    {companyid:'3329',name:'AXISCADES Technologies'},
    {companyid:'4745',name:'Jagsonpal Pharmaceuticals'},
    {companyid:'8458',name:'Astra Microwave Products'},
    {companyid:'15744',name:'SMS Pharmaceuticals'},
    {companyid:'13764',name:'EPL'},
    {companyid:'13851',name:'Coromandel International'},
    {companyid:'32683',name:'Prestige Estates Projects'},
    {companyid:'11435',name:'Gujarat Ambuja Exports'},
    {companyid:'45181',name:'Adhunik Industries'},
    {companyid:'14723',name:'HDFC Asset Management Company'},
    {companyid:'18903',name:'Redington (India)'},
    {companyid:'30972',name:'Vascon Engineers'},
    {companyid:'20073',name:'REFEX'},
    {companyid:'69232',name:'SPENCERS'},
    {companyid:'49439',name:'DBL'},
    {companyid:'30711',name:'DB Corp'},
    {companyid:'64847',name:'ADANIGREEN'},
    {companyid:'16646',name:'Welspun Enterprises'},
    {companyid:'32785',name:'Gravita India'},
    {companyid:'33348',name:'FCL'},
    {companyid:'49992',name:'Quick Heal'},
    {companyid:'32682',name:'Gyscoal Alloys'},
    {companyid:'6080',name:'Sundaram Multi Pap'},
    {companyid:'20692',name:'J Kumar Infraprojects'},
    {companyid:'4320',name:'IZMO'},
    {companyid:'11956',name:'Gujarat Industries Power'},
    {companyid:'18469',name:'Rites'},
    {companyid:'13611',name:'HLV LTD'},
    {companyid:'12627',name:'Gujarat Sidhee Cement'},
    {companyid:'13862',name:'Dalmia Bharat Sugar & Industries'},
    {companyid:'3318',name:'Larsen & Toubro Infotech'},
    {companyid:'6936',name:'Suprajit Engineering'},
    {companyid:'12315',name:'Radico Khaitan'},
    {companyid:'13621',name:'HSIL'},
    {companyid:'23',name:'Aegis Logistics'},
    {companyid:'8917',name:'Magma Fincorp'},
    {companyid:'13339',name:'HeidelbergCement India'},
    {companyid:'33871',name:'Vardhman Special Steels'},
    {companyid:'12882',name:'Unichem Laboratories'},
    {companyid:'16356',name:'Jyothy Labs'},
    {companyid:'13760',name:'Finolex Industries'},
    {companyid:'42268',name:'CARERATING'},
    {companyid:'7830',name:'Paramount Communications'},
    {companyid:'14533',name:'Gulshan Polyols'},
    {companyid:'6402',name:'Hatsun Agro Product Ltd'},
    {companyid:'4749',name:'PNB Housing Finance'},
    {companyid:'8965',name:'Mirza International'},
    {companyid:'16681',name:'Navin Fluorine International'},
    {companyid:'10144',name:'Patel Integrated Logistics'},
    {companyid:'13904',name:'Century Extrusions'},
    {companyid:'17027',name:'Vivimed Labs'},
    {companyid:'59894',name:'MEP'},
    {companyid:'7829',name:'Relaxo Footwear'},
    {companyid:'6056',name:'Vidhi Specialty Food Ingredients'},
    {companyid:'4722',name:'Bharat Dynamics'},
    {companyid:'12925',name:'Sudarshan Chemical Industries'},
    {companyid:'8464',name:'GIC Housing Finance'},
    {companyid:'20750',name:'Shriram EPC'},
    {companyid:'11282',name:'Tourism Finance Corporation'},
    {companyid:'12475',name:'Ugar Sugar Works'},
    {companyid:'3723',name:'Ajanta Pharma'},
    {companyid:'13489',name:'Kajaria Ceramics'},
    {companyid:'16571',name:'Multi Commodity Exchange of India'},
    {companyid:'10472',name:'Butterfly Gandhimathi Appliances Lt'},
    {companyid:'32621',name:'Oberoi Realty'},
    {companyid:'13045',name:'Saksoft'},
    {companyid:'32234',name:'Eros International Media'},
    {companyid:'31260',name:'Techno Electric & Engineering Co'},
    {companyid:'32069',name:'Inox wind'},
    {companyid:'13683',name:'GHCL'},
    {companyid:'30247',name:'Sadbhav Infrastructure Proj'},
    {companyid:'13994',name:'Banco Products (India)'},
    {companyid:'20272',name:'Kaveri Seed Company'},
    {companyid:'16050',name:'Sakuma'},
    {companyid:'12818',name:'West Coast Paper Mills'},
    {companyid:'4815',name:'KCP Sugar & Industries'},
    {companyid:'5459',name:'Minda Industries'},
    {companyid:'43500',name:'GENUSPAPER'},
    {companyid:'3601',name:'Datamatics Global Services'},
    {companyid:'2725',name:'Aptech'},
    {companyid:'13516',name:'Jay Shree Tea & Industries'},
    {companyid:'7942',name:'NRB Bearings'},
    {companyid:'15686',name:'Astral Poly Technik'},
    {companyid:'4529',name:'Cochin Shipyard'},
    {companyid:'13078',name:'JTEKT India'},
    {companyid:'1510',name:'Olectra Greentech'},
    {companyid:'2122',name:'Century Plyboards (India)'},
    {companyid:'20378',name:'BGR Energy Systems'},
    {companyid:'9206',name:'Hindustan Aeronautics'},
    {companyid:'55491',name:'ERIS'},
    {companyid:'34500',name:'ADVENZYMES'},
    {companyid:'13492',name:'Kalyani Steels'},
    {companyid:'8164',name:'63 Moons Technologies'},
    {companyid:'17641',name:'K.M.Sugar Mills'},
    {companyid:'64350',name:'BLS'},
    {companyid:'8311',name:'KEI Industries'},
    {companyid:'8609',name:'Pitti Engineering'},
    {companyid:'18027',name:'Godawari Power & Ispat'},
    {companyid:'2646',name:'Shoppers Stop'},
    {companyid:'7478',name:'Balaji Amines'},
    {companyid:'10948',name:'Simplex Infrastructures'},
    {companyid:'11334',name:'Igarashi Motors India'},
    {companyid:'6683',name:'APL Apollo Tubes'},
    {companyid:'13697',name:'Great Eastern Shipping Company'},
    {companyid:'13961',name:'Birla Corporation'},
    {companyid:'37676',name:'Prozone Intu Properties Ltd'},
    {companyid:'13597',name:'Zensar Technologies'},
    {companyid:'13274',name:'Pfizer'},
    {companyid:'4',name:'AVT Natural Products'},
    {companyid:'8534',name:'Kalpataru Power Transmission'},
    {companyid:'9126',name:'3P Land Holdings'},
    {companyid:'16459',name:'Steel Exchange India'},
    {companyid:'61359',name:'SHREEPUSHK'},
    {companyid:'21519',name:'Persistent Systems'},
    {companyid:'7770',name:'CCL Products (India) Ltd'},
    {companyid:'11764',name:'Godrej Industries'},
    {companyid:'13003',name:'Gokaldas Exports'},
    {companyid:'13155',name:'SRF'},
    {companyid:'30772',name:'D-Link (India)'},
    {companyid:'17635',name:'Bombay Rayon Fashions'},
    {companyid:'20444',name:'Transformers and Rectifiers (India)'},
    {companyid:'3184',name:'BF Utilities'},
    {companyid:'13536',name:'J B Chemicals & Pharmaceuticals'},
    {companyid:'7370',name:'Alankit'},
    {companyid:'11047',name:'Mastek'},
    {companyid:'13914',name:'CEAT'},
    {companyid:'8582',name:'Heritage Foods'},
    {companyid:'2299',name:'Maithan Alloys'},
    {companyid:'13662',name:'Harrisons Malayalam'},
    {companyid:'8493',name:'Goldiam International'},
    {companyid:'11965',name:'Swan Energy'},
    {companyid:'8581',name:'Caplin Point Laboratories Ltd'},
    {companyid:'13504',name:'Kabra Extrusiontechnik'},
    {companyid:'12694',name:'IL&FS Investment Managers'},
    {companyid:'32586',name:'GTPL Hathway'},
    {companyid:'12014',name:'Setco Automotive'},
    {companyid:'15045',name:'Arvind Fashions'},
    {companyid:'13033',name:'IIFL Finance Ltd'},
    {companyid:'8252',name:'Bal Pharma'},
    {companyid:'13859',name:'Kokuyo Camlin'},
    {companyid:'10413',name:'Kirloskar Ferrous Industries'},
    {companyid:'1942055',name:'PRAKASHPIPES'},
    {companyid:'17099',name:'Triveni Turbine'},
    {companyid:'12358',name:'Phoenix Mills'},
    {companyid:'11254',name:'Waterbase'},
    {companyid:'9771',name:'Godrej Agrovet'},
    {companyid:'18774',name:'Lumax Auto Technolgies'},
    {companyid:'13651',name:'Himatsingka Seide'},
    {companyid:'8890',name:'Som Distilleries & Breweries Ltd'},
    {companyid:'67525',name:'HGINFRA'},
    {companyid:'17103',name:'Mahindra CIE Automotive Ltd'},
    {companyid:'19146',name:'Ankit Metal & Power'},
    {companyid:'7772',name:'Cupid Ltd'},
    {companyid:'5590',name:'SATIN'},
    {companyid:'13942',name:'Blue Star'},
    {companyid:'10750',name:'Ashima'},
    {companyid:'29130',name:'Kirloskar Oil Engines'},
    {companyid:'16885',name:'Kamdhenu'},
    {companyid:'17998',name:'Allcargo Logistics'},
    {companyid:'4978',name:'Cyient Ltd'},
    {companyid:'44856',name:'Repco Home Finance'},
    {companyid:'4718',name:'Garden Reach'},
    {companyid:'12097',name:'Reliance Industrial Infrastructure'},
    {companyid:'13978',name:'Bajaj Electricals'},
    {companyid:'57414',name:'Sharda Cropchem Ltd'},
    {companyid:'17752',name:'Tejas Network'},
    {companyid:'56727',name:'Vishal Fabrics Ltd'},
    {companyid:'13551',name:'India Glycols'},
    {companyid:'13500',name:'KSB'},
    {companyid:'45489',name:'UFO'},
    {companyid:'6360',name:'Kitex Garments'},
    {companyid:'47561',name:'Future Lifestyle Fashions Ltd'},
    {companyid:'6576',name:'Shakti Pumps India'},
    {companyid:'13987',name:'Astrazeneca Pharma India'},
    {companyid:'3160',name:'Oracle Financial Services Software'},
    {companyid:'2820',name:'Cigniti Technologies Ltd'},
    {companyid:'11246',name:'Gufic BioSciences'},
    {companyid:'13394',name:'Murudeshwar Ceramics'},
    {companyid:'13781',name:'Uflex'},
    {companyid:'13576',name:'Indo Count Industries'},
    {companyid:'2796',name:'Zen Technologies'},
    {companyid:'38887',name:'Tribhovandas Bhimji Zaveri'},
    {companyid:'10573',name:'Kilitch Drugs (India)'},
    {companyid:'56366',name:'Skipper'},
    {companyid:'46612',name:'VRL Logistics'},
    {companyid:'17841',name:'Nitin Spinners'},
    {companyid:'68876',name:'Sumit Woods'},
    {companyid:'6650',name:'Rajesh Exports'},
    {companyid:'13759',name:'Finolex Cables'},
    {companyid:'8703',name:'Websol Energy System'},
    {companyid:'13854',name:'Cosmo Films'},
    {companyid:'11280',name:'Ashiana Housing'},
    {companyid:'11773',name:'Dredging Corporation of India'},
    {companyid:'66812',name:'Capacite'},
    {companyid:'13729',name:'Ginni Filaments'},
    {companyid:'13031',name:'Xchanging Solutions'},
    {companyid:'12676',name:'Nahar Poly Films'},
    {companyid:'13700',name:'Munjal Auto Industries'},
    {companyid:'6708',name:'The Byke Hospitality'},
    {companyid:'2256',name:'Manaksia'},
    {companyid:'3616',name:'Ramco Systems'},
    {companyid:'25028',name:'Texmo Pipes and Products'},
    {companyid:'18097',name:'Prime Focus'},
    {companyid:'6850',name:'Pokarna'},
    {companyid:'11399',name:'GTL'},
    {companyid:'6183',name:'Capri Global Capital Ltd'},
    {companyid:'66684',name:'APEX'},
    {companyid:'32988',name:'Ducon Infratechno'},
    {companyid:'19423',name:'Kolte Patil Developers'},
    {companyid:'50224',name:'Indiamart Intermesh'},
    {companyid:'47955',name:'NH'},
    {companyid:'13129',name:'Shree Cement'},
    {companyid:'39674',name:'Speciality Restaurants'},
    {companyid:'1760',name:'Arihant Superstructures'},
    {companyid:'31453',name:'Gallantt Ispat'},
    {companyid:'49',name:'AMRUTANJAN'},
    {companyid:'15854',name:'Aditya Birla Money'},
    {companyid:'61297',name:'AVADHSUGAR'},
    {companyid:'13098',name:'Siyaram Silk Mills'},
    {companyid:'13135',name:'Sakthi Sugars'},
    {companyid:'12125',name:'DCM Shriram Ltd'},
    {companyid:'41057',name:'IFGL Refractories'},
    {companyid:'3376',name:'Balaji Telefilms'},
    {companyid:'49702',name:'MAHESHWARI'},
    {companyid:'12993',name:'Star Paper Mills'},
    {companyid:'4358',name:'Compucom Software'},
    {companyid:'32615',name:'Arvind SmartSpaces'},
    {companyid:'16164',name:'Nelcast'},
    {companyid:'34532',name:'ZUARIAGRO'},
    {companyid:'11478',name:'Vardhman Polytex'},
    {companyid:'23241',name:'Mahindra Logistic'},
    {companyid:'13568',name:'IFB Industries'},
    {companyid:'45062',name:'HealthCare Global'},
    {companyid:'52803',name:'Wonderla Holidays Ltd'},
    {companyid:'13438',name:'McLeod Russel India'},
    {companyid:'11062',name:'PILITA'},
    {companyid:'6323',name:'JMA'},
    {companyid:'19684',name:'Sutlej Textiles and Industries'},
    {companyid:'18715',name:'Motilal Oswal Financial Services'},
    {companyid:'3605',name:'Sasken Technologies'},
    {companyid:'20136',name:'Puravankara'},
    {companyid:'6043',name:'California Software Company'},
    {companyid:'7524',name:'Bhageria Inds'},
    {companyid:'9003',name:'Mayur Uniquoters'},
    {companyid:'58299',name:'MONTECARLO'},
    {companyid:'11667',name:'L G Balakrishnan & Bros'},
    {companyid:'12108',name:'Texmaco Infrastructure & Holdings'},
    {companyid:'8578',name:'Shreyas Shipping & Logistics'},
    {companyid:'13077',name:'Somany Ceramics'},
    {companyid:'4594',name:'India Tourism Dev Corp'},
    {companyid:'5778',name:'SUNDARMHLD'},
    {companyid:'67198',name:'Vertoz Advertising'},
    {companyid:'13950',name:'Oswal Green Tech'},
    {companyid:'12527',name:'Navneet Education Ltd'},
    {companyid:'34103',name:'Kridhan Infra'},
    {companyid:'3295',name:'TajGVK Hotels & Resorts'},
    {companyid:'65301',name:'LASA'},
    {companyid:'39695',name:'SALASAR'},
    {companyid:'13713',name:'Kansai Nerolac Paints'},
    {companyid:'11318',name:'Hercules Hoists'},
    {companyid:'13874',name:'Clariant Chemiclas (India)'},
    {companyid:'13830',name:'Dhanuka Agritech'},
    {companyid:'50116',name:'CL Educate'},
    {companyid:'6187',name:'Lincoln Pharma'},
    {companyid:'10473',name:'Symphony'},
    {companyid:'49560',name:'Future Supply'},
    {companyid:'12199',name:'Maharashtra Seamless'},
    {companyid:'16087',name:'HT Media'},
    {companyid:'12962',name:'Sundram Fasteners'},
    {companyid:'13945',name:'Bombay Burmah'},
    {companyid:'64019',name:'GOKULAGRO'},
    {companyid:'20794',name:'Globus Spirits'},
    {companyid:'13909',name:'Carborundum Universal'},
    {companyid:'8081',name:'Sarla Performance Fibers'},
    {companyid:'13345',name:'Orient Abrasives'},
    {companyid:'32357',name:'Cantabil Retail India'},
    {companyid:'3700',name:'Dynacons Systems & Solutions'},
    {companyid:'8771',name:'CCHHL'},
    {companyid:'16639',name:'Mahindra Holidays & Resorts India'},
    {companyid:'19484',name:'Hinduja Global Solutions'},
    {companyid:'34403',name:'Brooks Laboratories'},
    {companyid:'13800',name:'Alstom T&D India'},
    {companyid:'13470',name:'Kirloskar Brothers'},
    {companyid:'13805',name:'Elgi Equipments'},
    {companyid:'18666',name:'ENIL'},
    {companyid:'30581',name:'Spandana Sphoorty Financial'},
    {companyid:'67404',name:'Amber Enterprises'},
    {companyid:'13315',name:'Oswal Agro Mills'},
    {companyid:'10667',name:'Steel Strips Wheels'},
    {companyid:'11712',name:'Indian Metals & Ferro Alloys'},
    {companyid:'55515',name:'QUESS'},
    {companyid:'4366',name:'Intense Technologies'},
    {companyid:'17799',name:'Dynemic Products'},
    {companyid:'4407',name:'Shree Rama Multi-Tech'},
    {companyid:'792',name:'Indoco Remedies'},
    {companyid:'65885',name:'DOLLAR'},
    {companyid:'2825',name:'Newgen Software'},
    {companyid:'8110',name:'Optiemus Infracom'},
    {companyid:'23263',name:'BHAGYAPROP'},
    {companyid:'6074',name:'Viji Fin'},
    {companyid:'12950',name:'Transport Corporation of India'},
    {companyid:'4788',name:'Ind-Swift Laboratories'},
    {companyid:'15334',name:'Omaxe'},
    {companyid:'5088',name:'KIOCL'},
    {companyid:'13282',name:'Polyplex Corporation'},
    {companyid:'13126',name:'Shalimar Paints'},
    {companyid:'16508',name:'TV Today Network'},
    {companyid:'31869',name:'Prakash Steelage'},
    {companyid:'10778',name:'Apcotex Industries'},
    {companyid:'29124',name:'Excel Realty N'},
    {companyid:'13321',name:'Oriental Hotels'},
    {companyid:'65742',name:'Shankara Building'},
    {companyid:'7382',name:'OM INFRA'},
    {companyid:'18693',name:'Maan Aluminium'},
    {companyid:'8152',name:'La Opala RG'},
    {companyid:'13229',name:'Sarda Energy & Minerals'},
    {companyid:'16916',name:'Renaissance Global'},
    {companyid:'12071',name:'Ajmera Realty & Infra India'},
    {companyid:'3714',name:'GE Power India Limited'},
    {companyid:'65829',name:'PANACHEDIGI'},
    {companyid:'12827',name:'Venky (India)'},
    {companyid:'57482',name:'Shemaroo Entertainment Ltd'},
    {companyid:'49516',name:'Hi-Tech Pipes'},
    {companyid:'5864',name:'Atul Auto'},
    {companyid:'8442',name:'Assoc.Alcohols'},
    {companyid:'12183',name:'Timken India'},
    {companyid:'12855',name:'Visaka Industries'},
    {companyid:'17843',name:'Royal Orchid Hotels'},
    {companyid:'4586',name:'Poly Medicure'},
    {companyid:'18029',name:'Khadim India'},
    {companyid:'66510',name:'Total Transport'},
    {companyid:'10579',name:'BPL'},
    {companyid:'13370',name:'NELCO'},
    {companyid:'68496',name:'Varroc Engineering'},
    {companyid:'1850579',name:'XELPMDESIANTECH'},
    {companyid:'10258',name:'Birla Cable'},
    {companyid:'55290',name:'Astron Paper'},
    {companyid:'12150',name:'Apar Industries'},
    {companyid:'16458',name:'Mangalam Drugs'},
    {companyid:'13687',name:'GMM Pfaudler'},
    {companyid:'23260',name:'Essar Shipping'},
    {companyid:'12743',name:'Tata Steel Long Products'},
    {companyid:'7142',name:'Nucleus Software Exports'},
    {companyid:'11065',name:'Mahindra EPC Irrigation'},
    {companyid:'13587',name:'Indian Hume Pipe Company'},
    {companyid:'8043',name:'Venus Remedies'},
    {companyid:'8348',name:'Trigyn Technologies'},
    {companyid:'24724',name:'Mold-Tek Packaging'},
    {companyid:'15290',name:'Uttam Sugar Mills'},
    {companyid:'34185',name:'Inventure Growth & Securities'},
    {companyid:'60265',name:'SCFL'},
    {companyid:'1201',name:'ISMT'},
    {companyid:'13715',name:'Glaxosmithkline Pharmaceuticals'},
    {companyid:'15821',name:'Hilton Metal Forging'},
    {companyid:'11339',name:'FELDVR'},
    {companyid:'18210',name:'Ruchira Papers'},
    {companyid:'21067',name:'Kiri Industries'},
    {companyid:'14040',name:'ABB India Ltd'},
    {companyid:'5962',name:'Apollo Pipes'},
    {companyid:'7978',name:'Sanghvi Movers'},
    {companyid:'9028',name:'Srikalahasthi Pipes'},
    {companyid:'10490',name:'R S Software (India)'},
    {companyid:'13112',name:'Seshasayee Paper & Boards'},
    {companyid:'65012',name:'GNA'},
    {companyid:'13029',name:'Gateway Distriparks'},
    {companyid:'13127',name:'Shanthi Gears'},
    {companyid:'10915',name:'Ratnamani Metals & Tubes'},
    {companyid:'20176',name:'Kuantum Papers'},
    {companyid:'24222',name:'Indiabulls Integrated Ser'},
    {companyid:'12854',name:'Vinyl Chemicals India'},
    {companyid:'4994',name:'Rupa & Company'},
    {companyid:'8165',name:'Thermax'},
    {companyid:'30973',name:'Emmbi Industries Ltd'},
    {companyid:'30660',name:'MBL Infrastructures'},
    {companyid:'31845',name:'Emami Realty'},
    {companyid:'67960',name:'Fine Organics'},
    {companyid:'68656',name:'Affle (India)'},
    {companyid:'8988',name:'G M Breweries'},
    {companyid:'13313',name:'Huhtamaki India'},
    {companyid:'3527',name:'Mahindra Lifespace Developers'},
    {companyid:'11557',name:'Ramco Industries'},
    {companyid:'13336',name:'Nahar Spinning Mills'},
    {companyid:'13404',name:'Peninsula Land'},
    {companyid:'29831',name:'EXPLEO SOLUTIONS'},
    {companyid:'13863',name:'Deccan Cements'},
    {companyid:'10574',name:'Krebs Biochemicals & Industries'},
    {companyid:'44',name:'Superhouse Ltd'},
    {companyid:'18348',name:'Sicagen India'},
    {companyid:'13330',name:'Nestle India'},
    {companyid:'14039',name:'Asahi India Glass'},
    {companyid:'19004',name:'Nandan Denim Ltd'},
    {companyid:'12612',name:'Andhra Sugars'},
    {companyid:'45671',name:'TCNSBRANDS'},
    {companyid:'12969',name:'Supreme Industries'},
    {companyid:'1942599',name:'Neogen Chemicals'},
    {companyid:'15558',name:'Ramky Infrastructure'},
    {companyid:'60181',name:'AKASH'},
    {companyid:'11492',name:'GPT Infraprojects'},
    {companyid:'34499',name:'TD Power Systems'},
    {companyid:'8826',name:'Jindal Poly Films'},
    {companyid:'12172',name:'IG Petrochemicals'},
    {companyid:'11441',name:'State Trading Corporation of India'},
    {companyid:'5055',name:'Orient Bell'},
    {companyid:'52891',name:'TMRVL'},
    {companyid:'5030',name:'SKM Egg Products Export (India)'},
    {companyid:'636',name:'Hindustan Media Ventures'},
    {companyid:'34',name:'Alkyl Amines Chemicals'},
    {companyid:'7060',name:'Emami Paper Mills'},
    {companyid:'529',name:'GULFPETRO'},
    {companyid:'67087',name:'TREJHARA'},
    {companyid:'69233',name:'RPSG VENTURES'},
    {companyid:'12051',name:'ADF Foods'},
    {companyid:'5350',name:'Kothari Petrochemicals'},
    {companyid:'7037',name:'Sambhaav Media'},
    {companyid:'56123',name:'SAKAR'},
    {companyid:'8650',name:'NACL Inds'},
    {companyid:'15271',name:'Gallantt Metal'},
    {companyid:'1846307',name:'Dalmia Bharat'},
    {companyid:'32314',name:'Sastasundar Vent'},
    {companyid:'12195',name:'Kirloskar Electric Company'},
    {companyid:'67230',name:'TIINDIA'},
    {companyid:'8642',name:'Kamat Hotels (India)'},
    {companyid:'22730',name:'Alkali Metals'},
    {companyid:'15487',name:'Atlanta'},
    {companyid:'61181',name:'POWERMECH'},
    {companyid:'17663',name:'SORIL Infra Resources'},
    {companyid:'8570',name:'Onward Technologies'},
    {companyid:'13903',name:'Century Enka'},
    {companyid:'42221',name:'Veto Switchgears and Cables'},
    {companyid:'13607',name:'Sanofi India'},
    {companyid:'13120',name:'Sagar Cements'},
    {companyid:'11911',name:'Bosch'},
    {companyid:'2542',name:'Megasoft'},
    {companyid:'31138',name:'Intrasoft Technologies'},
    {companyid:'5226',name:'Vaibhav Global Ltd'},
    {companyid:'61577',name:'PDMJEPAPER'},
    {companyid:'8690',name:'Surana Telecom and Power'},
    {companyid:'10609',name:'Mindteck (India)'},
    {companyid:'12127',name:'Mawana Sugars'},
    {companyid:'11310',name:'Precision Wires (India)'},
    {companyid:'10947',name:'VLS Finance'},
    {companyid:'13590',name:'Linde India Ltd'},
    {companyid:'8318',name:'DFM Foods'},
    {companyid:'6849',name:'Zodiac Clothing Company'},
    {companyid:'21603',name:'LUXIND'},
    {companyid:'67713',name:'Mittal Life Style'},
    {companyid:'19033',name:'Insecticides (India)'},
    {companyid:'860',name:'Visa Steel'},
    {companyid:'12008',name:'Salzer Electron'},
    {companyid:'65729',name:'AIRAN'},
    {companyid:'20477',name:'Aries Agro'},
    {companyid:'10966',name:'APCL'},
    {companyid:'22472',name:'20 Microns'},
    {companyid:'12922',name:'Subros'},
    {companyid:'1942561',name:'ABBPP&SLTD'},
    {companyid:'11897',name:'Vardhman Textiles'},
    {companyid:'4968',name:'N R Agarwal Industries'},
    {companyid:'13518',name:'Jindal Drilling & Industries'},
    {companyid:'6511',name:'LAMBODHARA'},
    {companyid:'15272',name:'STL Global'},
    {companyid:'13540',name:'Tata Investment Corporation'},
    {companyid:'8309',name:'Aro Granite Industries'},
    {companyid:'12522',name:'DPSC'},
    {companyid:'17703',name:'Mcdowell Holdings'},
    {companyid:'32206',name:'Rushil Decor'},
    {companyid:'22221',name:'5PAISA'},
    {companyid:'1944331',name:'Somany Home Innovation'},
    {companyid:'12858',name:'Vadilal Industries'},
    {companyid:'66744',name:'Bharat Road'},
    {companyid:'32434',name:'Bedmutha Industries'},
    {companyid:'15509',name:'V2 Retail'},
    {companyid:'50719',name:'Agri-Tech (India) Ltd'},
    {companyid:'13977',name:'Bajaj Holdings & Investment'},
    {companyid:'11109',name:'Ansal Properties & Infrastructure'},
    {companyid:'32275',name:'Career Point'},
    {companyid:'4796',name:'Donear Industries'},
    {companyid:'5657',name:'Archies'},
    {companyid:'13860',name:'OAL'},
    {companyid:'67647',name:'KARDACONST'},
    {companyid:'19863',name:'Astec Lifesciences'},
    {companyid:'13821',name:'Dharani Sugars & Chemicals'},
    {companyid:'12919',name:'Talbros Automotive Components'},
    {companyid:'34368',name:'Tree House Education & Accessories'},
    {companyid:'12889',name:'Cholamandalam Financial'},
    {companyid:'59671',name:'Infobeans Tech'},
    {companyid:'33202',name:'Lovable Lingerie'},
    {companyid:'1948392',name:'Vishwaraj Sugar Industries'},
    {companyid:'50526',name:'Sanco Inds'},
    {companyid:'11',name:'Aban Offshore'},
    {companyid:'14081',name:'JBM Auto'},
    {companyid:'47196',name:'Jash Engg'},
    {companyid:'4201',name:'SIGIND'},
    {companyid:'18892',name:'Technocraft Industries (India)'},
    {companyid:'50720',name:'Nath Bio-Genes (India) Ltd'},
    {companyid:'15504',name:'Deep Industries'},
    {companyid:'13981',name:'BASF India'},
    {companyid:'20138',name:'KPR Mill'},
    {companyid:'7132',name:'Arman Financial Serv'},
    {companyid:'53390',name:'Chemfab Alkalis'},
    {companyid:'13797',name:'Everest Industries'},
    {companyid:'8235',name:'Muthoot Capital Services'},
    {companyid:'3043',name:'Vardhman Acrylics'},
    {companyid:'16774',name:'Ramkrishna Forgings'},
    {companyid:'30991',name:'Arss Infrastructure Projects'},
    {companyid:'13778',name:'Excel Industries'},
    {companyid:'16783',name:'NDTV'},
    {companyid:'65225',name:'Agro Phos'},
    {companyid:'6349',name:'SPL Industries'},
    {companyid:'8508',name:'Selan Exploration Technology'},
    {companyid:'16868',name:'Emkay Global Financial Services'},
    {companyid:'12928',name:'TRF'},
    {companyid:'8711',name:'TTK Prestige'},
    {companyid:'6634',name:'Hisar Metal Inds'},
    {companyid:'13323',name:'Omax Autos'},
    {companyid:'13704',name:'Saregama India'},
    {companyid:'13460',name:'Windsor Machines'},
    {companyid:'12878',name:'Ucal Fuel Systems'},
    {companyid:'16240',name:'R Systems International'},
    {companyid:'3790',name:'Galaxy Surfactants'},
    {companyid:'11894',name:'Mangalam Cement'},
    {companyid:'68848',name:'Dangee Dums'},
    {companyid:'12155',name:'GANECOS'},
    {companyid:'12002',name:'Nilkamal'},
    {companyid:'34404',name:'Elgi Rubber Company'},
    {companyid:'22',name:'Ador Welding'},
    {companyid:'13959',name:'Bharat Gears'},
    {companyid:'11709',name:'India Nippon Electricals'},
    {companyid:'12458',name:'MPS'},
    {companyid:'12765',name:'Albert David'},
    {companyid:'12870',name:'Universal Cables'},
    {companyid:'14744',name:'Cambridge Technology Enterprises'},
    {companyid:'46318',name:'Teamlease'},
    {companyid:'13716',name:'Goa Carbon'},
    {companyid:'3836',name:'SECUREKLOUD TECHNOLOGIES'},
    {companyid:'10416',name:'Mahamaya Steel Inds'},
    {companyid:'13232',name:'RSWM'},
    {companyid:'53',name:'ANDHRA PAPER'},
    {companyid:'10454',name:'Alphageo (India)'},
    {companyid:'60',name:'Ansal Housing'},
    {companyid:'11355',name:'Dhunseri Ventures'},
    {companyid:'8699',name:'Shriram City Union Finance'},
    {companyid:'32964',name:'R P P Infra Projects'},
    {companyid:'20697',name:'Cords Cable Industries'},
    {companyid:'762',name:'Page Industries'},
    {companyid:'21324',name:'Gokul Refoils and Solvent'},
    {companyid:'18522',name:'SATIA'},
    {companyid:'67463',name:'South West Pinn'},
    {companyid:'412',name:'Orissa Minerals Development Company'},
    {companyid:'12963',name:'Sundaram Finance'},
    {companyid:'1942056',name:'Digicontent Ltd'},
    {companyid:'33078',name:'Jubilant Industries'},
    {companyid:'13169',name:'RUCHI'},
    {companyid:'12307',name:'Shreyans Industries'},
    {companyid:'8120',name:'Privi Specility Chemicals'},
    {companyid:'6308',name:'Coral India Finance & Housing'},
    {companyid:'13707',name:'Godfrey Phillips India'},
    {companyid:'13261',name:'Pressman Advertising Ltd'},
    {companyid:'67273',name:'ONEPOINT'},
    {companyid:'8985',name:'Blue Dart Express'},
    {companyid:'13385',name:'Munjal Showa'},
    {companyid:'5',name:'INEOS Styrolution India'},
    {companyid:'3675',name:'Tera Software'},
    {companyid:'66811',name:'Matrimony'},
    {companyid:'13723',name:'Garware Technical Fibres'},
    {companyid:'8673',name:'Bhartiya International'},
    {companyid:'17637',name:'AIA Engineering'},
    {companyid:'61308',name:'MAGADHSUGAR'},
    {companyid:'4266',name:'Responsive Industries'},
    {companyid:'5584',name:'Pioneer Distilleries'},
    {companyid:'34553',name:'Manaksia Steels'},
    {companyid:'30963',name:'Thangamayil Jewellery'},
    {companyid:'8594',name:'VISHNU'},
    {companyid:'16847',name:'J K Cements'},
    {companyid:'19051',name:'Asahi Songwon Colors'},
    {companyid:'13541',name:'Indo Rama Synthetics (India)'},
    {companyid:'11381',name:'MRF'},
    {companyid:'10961',name:'MENONBE'},
    {companyid:'18395',name:'Nahar Capital and Financial Service'},
    {companyid:'65069',name:'TCI Express'},
    {companyid:'11303',name:'CRISIL'},
    {companyid:'46114',name:'SANTECHNO'},
    {companyid:'13641',name:'GFL Ltd'},
    {companyid:'20144',name:'Sree Rayalseema Hi Strength Hypo'},
    {companyid:'9165',name:'HESTERBIO'},
    {companyid:'4571',name:'Electrotherm (India)'},
    {companyid:'13709',name:'Grindwel Norton'},
    {companyid:'10222',name:'Anik Industries'},
    {companyid:'10663',name:'Pioneer Embroideries'},
    {companyid:'5489',name:'Swelect Energy Systems'},
    {companyid:'15913',name:'TGB Banquets and Hotels Ltd'},
    {companyid:'13647',name:'Hind Rectifiers'},
    {companyid:'11165',name:'Shree Rama Newsprint Ltd'},
    {companyid:'24325',name:'Future Market Network'},
    {companyid:'13614',name:'HIL'},
    {companyid:'13159',name:'Safari Industries (India)'},
    {companyid:'32924',name:'BF Investment'},
    {companyid:'65766',name:'Creative Peripherals and Distributi'},
    {companyid:'13965',name:'BSL'},
    {companyid:'68035',name:'The Anup Engineering'},
    {companyid:'13558',name:'Ingersoll-Rand (India)'},
    {companyid:'13968',name:'Bharat Bijlee'},
    {companyid:'64531',name:'SPAL'},
    {companyid:'21510',name:'LEHIL'},
    {companyid:'10806',name:'Seya Industries'},
    {companyid:'17610',name:'Bannari Amman Spinning Mills'},
    {companyid:'42186',name:'Simbhaoli Sugars'},
    {companyid:'18139',name:'Fiem Industries'},
    {companyid:'33055',name:'Ravi Kumar Distilleries'},
    {companyid:'4303',name:'Kanani Industries'},
    {companyid:'1057',name:'APOLSINHOT'},
    {companyid:'21946',name:'Kaya'},
    {companyid:'33203',name:'Mas Financial Services'},
    {companyid:'9097',name:'TPL Plastech'},
    {companyid:'15273',name:'Malu Paper Mills'},
    {companyid:'9100',name:'Umang Dairies'},
    {companyid:'16820',name:'Rane (Madras)'},
    {companyid:'39765',name:'SANGINITA'},
    {companyid:'11243',name:'KDDL'},
    {companyid:'12309',name:'Kakatiya Cements Sugar & Industries'},
    {companyid:'11314',name:'AYM Syntex'},
    {companyid:'5704',name:'Ahluwalia Contracts (India)'},
    {companyid:'2390',name:'North Eastern Carrying Corp'},
    {companyid:'18866',name:'Autoline Industries'},
    {companyid:'13937',name:'Abbott India'},
    {companyid:'7701',name:'Sterling Tools'},
    {companyid:'8506',name:'Damodar Inds'},
    {companyid:'12961',name:'SML Isuzu'},
    {companyid:'10267',name:'Mukand Engineers'},
    {companyid:'8634',name:'AksharChem (India)'},
    {companyid:'67869',name:'INDOSTCAFIN'},
    {companyid:'13139',name:'SKF India'},
    {companyid:'13868',name:'DCM'},
    {companyid:'19090',name:'Tarmat'},
    {companyid:'8233',name:'Seamec'},
    {companyid:'11316',name:'Ausom Enterprise'},
    {companyid:'13708',name:'Federal-Mogul Goetze (India)'},
    {companyid:'4747',name:'SREEL'},
    {companyid:'44030',name:'V-Mart Retail Ltd'},
    {companyid:'12960',name:'Swaraj Engines'},
    {companyid:'13780',name:'Schaeffler India'},
    {companyid:'17795',name:'GeeCee Ventures'},
    {companyid:'8428',name:'Orbit Exports Ltd'},
    {companyid:'4800',name:'Rossell India'},
    {companyid:'12747',name:'De Nora India'},
    {companyid:'13646',name:'Hind.Foods'},
    {companyid:'11477',name:'VST Tillers Tractors'},
    {companyid:'13219',name:'Rane Holdings'},
    {companyid:'65889',name:'Zota Health'},
    {companyid:'13976',name:'Beardsell'},
    {companyid:'13975',name:'Bayer CropScience'},
    {companyid:'12819',name:'Vindhya Telelinks'},
    {companyid:'6170',name:'Prajay Engineers Syndicate'},
    {companyid:'5598',name:'Ambika Cotton Mills'},
    {companyid:'13984',name:'Automotive Axles'},
    {companyid:'56770',name:'Gulf Oil Lubricants India Ltd'},
    {companyid:'13610',name:'IFB Agro Industries'},
    {companyid:'15885',name:'Steel City Securities'},
    {companyid:'49786',name:'DNAMEDIA'},
    {companyid:'13320',name:'Oriental Carbon & Chem'},
    {companyid:'4775',name:'Lypsa Gems & Jewellery '},
    {companyid:'10759',name:'Jayant Agro Organics'},
    {companyid:'12794',name:'Wheels India'},
    {companyid:'65362',name:'SMSLIFE'},
    {companyid:'10599',name:'Mold-Tek Technologies'},
    {companyid:'9128',name:'Savita Oil Technologies'},
    {companyid:'13601',name:'Akzo Nobel India'},
    {companyid:'12727',name:'Kingfa Science & Techno'},
    {companyid:'12987',name:'TVS Srichakra'},
    {companyid:'13816',name:'Dynamatic Technologies'},
    {companyid:'7583',name:'Chembond Chemicals'},
    {companyid:'47614',name:'GRNLAMIND'},
    {companyid:'1311',name:'ICRA'},
    {companyid:'2',name:'TCPL Packaging'},
    {companyid:'61459',name:'Sheela Foam'},
    {companyid:'2123',name:'Sharda Motor Industries'},
    {companyid:'33207',name:'Vaswani Industries'},
    {companyid:'21601',name:'Rane Brake Lining'},
    {companyid:'13996',name:'Banswara Syntex'},
    {companyid:'15493',name:'Voltamp Transformers'},
    {companyid:'13270',name:'EIH Associated Hotels'},
    {companyid:'10900',name:'Cubex Tubings'},
    {companyid:'67222',name:'Ice Make'},
    {companyid:'15283',name:'Solar Industries India'},
    {companyid:'13602',name:'GOCLCORP'},
    {companyid:'12586',name:'Williamson Magor & Company'},
    {companyid:'4903',name:'Tokyo Plast Intl'},
    {companyid:'12915',name:'Honeywell Automation India'},
    {companyid:'15235',name:'Indo Tech Transformers'},
    {companyid:'13534',name:'Jay Bharat Maruti'},
    {companyid:'12777',name:'Weizmann'},
    {companyid:'12710',name:'Hitachi Home and Life Solutions (In'},
    {companyid:'14033',name:'Asian Hotels'},
    {companyid:'11390',name:'Madhav Marbles and Granites'},
    {companyid:'12785',name:'Super Spinning Mills'},
    {companyid:'10165',name:'Premier Polyfilm'},
    {companyid:'10677',name:'Vesuvius India'},
    {companyid:'12333',name:'Suryalakhmi Cotton Mills'},
    {companyid:'22217',name:'IIFL Wealth Management'},
    {companyid:'12951',name:'TIL'},
    {companyid:'13241',name:'AMJ Land Holdings'},
    {companyid:'12577',name:'Advani Hotels & Resorts (India)'},
    {companyid:'7214',name:'Alicon Castalloy'},
    {companyid:'1181',name:'Inspirisys Solutions'},
    {companyid:'3557',name:'Mukta Arts'},
    {companyid:'11904',name:'Lumax Industries'},
    {companyid:'20732',name:'Bang Overseas'},
    {companyid:'29943',name:'TV Vision'},
    {companyid:'10489',name:'Control Print'},
    {companyid:'4119',name:'Allsec Technologies'},
    {companyid:'8663',name:'Rajratan Global Wire'},
    {companyid:'7041',name:'LINCPEN'},
    {companyid:'10303',name:'Nagreeka Exports'},
    {companyid:'13801',name:'Esab India'},
    {companyid:'2610',name:'Next Mediaworks'},
    {companyid:'12690',name:'3M India'},
    {companyid:'12571',name:'T T'},
    {companyid:'11421',name:'Maharashtra Scooters'},
    {companyid:'11018',name:'Consolidated Finvest & Holdings'},
    {companyid:'9024',name:'M M Forgings'},
    {companyid:'41675',name:'PDS Multinational Fashions Ltd'},
    {companyid:'12158',name:'Agro Tech Foods'},
    {companyid:'13443',name:'Lakshmi Machine Works'},
    {companyid:'7875',name:'Jocil'},
    {companyid:'2651',name:'Repro India'},
    {companyid:'13625',name:'Hindustan Composites'},
    {companyid:'64202',name:'Sagardeep Alloys'},
    {companyid:'9017',name:'Poddar Pigments'},
    {companyid:'10640',name:'Hitech Corp'},
    {companyid:'7973',name:'Themis Medicare'},
    {companyid:'66896',name:'Aarvi Encon'},
    {companyid:'13819',name:'Procter & Gamble Health'},
    {companyid:'3354',name:'Smartlink Holdings'},
    {companyid:'13247',name:'Punjab Chemicals and Crop Protectio'},
    {companyid:'13567',name:'Gillette India'},
    {companyid:'8109',name:'The Investment Trust Of India'},
    {companyid:'13048',name:'Morarjee Textiles'},
    {companyid:'11606',name:'Mohit Industries'},
    {companyid:'42652',name:'WORTHPER'},
    {companyid:'13253',name:'P & G Hygiene'},
    {companyid:'12825',name:'VST Industries'},
    {companyid:'66833',name:'DPWIRES'},
    {companyid:'6615',name:'Almondz Global Securities'},
    {companyid:'57791',name:'DHUNTEAIND'},
    {companyid:'13317',name:'Nahar Industrial Enterprises'},
    {companyid:'12921',name:'Sundaram Clayton'},
    {companyid:'13101',name:'Honda India Power Products'},
    {companyid:'8241',name:'Banaras Beads'},
    {companyid:'2721',name:'Cera Sanitaryware'},
    {companyid:'11437',name:'Motor & General Finance'},
    {companyid:'21609',name:'Rane Engine Valve'},
    {companyid:'12353',name:'Ruby Mills'},
    {companyid:'12255',name:'Balaxi Pharmaceuticals'},
    {companyid:'10300',name:'Patspin India'},
    {companyid:'12784',name:'Precot'},
    {companyid:'67475',name:'Banka Bioloo'},
    {companyid:'8270',name:'DB International Stock Brokers'},
    {companyid:'55881',name:'MMPINDS'},
    {companyid:'12239',name:'Industrial Investment Trust'},
    {companyid:'13739',name:'Golden Tobacco'},
    {companyid:'40095',name:'GEEKAYWIRE'},
    {companyid:'7542',name:'Remsons Industries'},
    {companyid:'22706',name:'Wabco India'},
    {companyid:'10986',name:'Bharat Rasayan'},
    {companyid:'12574',name:'Kirloskar Industries'},
    {companyid:'13730',name:'Gandhi Special Tubes'},
    {companyid:'15701',name:'Summit Securities'},
    {companyid:'67050',name:'D P ABHUSHAN'},
    {companyid:'13419',name:'Mangalam Timber Products'},
    {companyid:'11759',name:'GRPLTD'},
    {companyid:'22877',name:'Asian Hotels (East)'},
    {companyid:'12056',name:'Pilani Investment & Inds Corp'},
    {companyid:'58',name:'Shiva Texyarn'},
    {companyid:'8108',name:'Twenty First Century Management'},
    {companyid:'12795',name:'Kennametal India'},
    {companyid:'7988',name:'Kothari Products'},
    {companyid:'3211',name:'Ponni Sugars (Erode)'},
    {companyid:'12942',name:'Tainwala Chemicals & Plastics'},
    {companyid:'12771',name:'GROBTEA'},
    {companyid:'61406',name:'GANGESSEC'},
    {companyid:'22876',name:'Asian Hotels (West)'},
    {companyid:'8584',name:'Centum Electronics'},
    {companyid:'10383',name:'Gujarat Apollo Industries'},
    {companyid:'11213',name:'Plastiblends India'},
    {companyid:'13888',name:'DIC India'},
    {companyid:'10444',name:'Orient Press'},
    {companyid:'41966',name:'Universus Photo Imagings'},
    {companyid:'4342',name:'Accelya Solutions'},
    {companyid:'12263',name:'Tide Water Oil Company (India)'},
    {companyid:'12973',name:'Sundaram Brake Linings'},
    {companyid:'17007',name:'JSW Holdings Ltd'},
    {companyid:'5648',name:'Salona Cotspin'},
    {companyid:'13180',name:'Revathi Equipment'},
    {companyid:'18329',name:'Pearl Global Industries'},
    {companyid:'11753',name:'Eimco Elecon (India)'},
    {companyid:'13995',name:'Bannari Amman Sugars'},
    {companyid:'40463',name:'KRISHANA'},
    {companyid:'12938',name:'TTK Healthcare'},
    {companyid:'64934',name:'BIGBLOC'},
    {companyid:'15767',name:'Raj Television Network'},
    {companyid:'33198',name:'Dhunseri Investments'},
    {companyid:'34119',name:'EBIXCASH WORLD MONEY'},
    {companyid:'12697',name:'Manugraph India'},
    {companyid:'61454',name:'PALASHSEC'},
    {companyid:'8933',name:'Zenith Exports'},
    {companyid:'13304',name:'Pearl Polymers'},
    {companyid:'31229',name:'GB Global'},
    {companyid:'12912',name:'Tasty Bite Eatables'},
    {companyid:'13773',name:'DELTA MANUFACTURING'},
    {companyid:'8863',name:'KEYNOTE FINANCIAL'},
    {companyid:'13521',name:'Nalwa Sons'},
    {companyid:'8743',name:'Zodiac-JRD-MRJ'},
    {companyid:'11777',name:'Foseco India'},
    {companyid:'5318',name:'NXTDIGITAL'},
    {companyid:'12656',name:'Vardhman Holdings'},
    {companyid:'5814',name:'Khandwala Securities'},
    {companyid:'68824',name:'Aaron Inds'},
    {companyid:'15299',name:'Kewal Kiran Clothing'},
    {companyid:'29171',name:'TCI Developers'},
    {companyid:'9033',name:'N K Industries'},
    {companyid:'11879',name:'Aspinwall & Company'},
    {companyid:'8819',name:'Times Guaranty'},
    {companyid:'13728',name:'Gillanders Arbuthnot & Co'},
    {companyid:'13564',name:'Indo National Ltd'},
    {companyid:'8491',name:'United Nilgiri Tea'},
    {companyid:'67460',name:'SINTERIND'},
    {companyid:'13665',name:'SIL Investments'},
    {companyid:'8483',name:'Sandesh'},
    {companyid:'32926',name:'Kalyani Investment Company'},
    {companyid:'6672',name:'Arihant Foundations & Housing'},
    {companyid:'2449',name:'ABMINTLTD'},
    {companyid:'12544',name:'Wendt India'},
    {companyid:'30346',name:'Welspun Investments & Commercials '},
    {companyid:'11620',name:'Naga Dhunseri Group'},
    {companyid:'13572',name:'Indian Card Clothing Company'},
    {companyid:'4176',name:'LFIC'},
    {companyid:'7373',name:'Rajdarshan Industries'},
    {companyid:'4924',name:'N B I Industrial Fin Co'},
    {companyid:'63176',name:'Sab Events'},
    {companyid:'12806',name:'W.S.Industries (India)'},
    {companyid:'13917',name:'Cipla'},
    {companyid:'61545',name:'Laurus'},
    {companyid:'13841',name:'Dr Reddys Laboratories'},
    {companyid:'10737',name:'JSW Ispat Special Products'},
    {companyid:'6967',name:'Panacea Biotec'},
    {companyid:'13526',name:'JBF Industries'},
    {companyid:'60244',name:'THYROCARE'},
    {companyid:'8499',name:'Jayaswal Neco Industries'},
    {companyid:'13934',name:'Britannia Industries'},
    {companyid:'1944774',name:'Gujarat Fluorochemicals'},
    {companyid:'10587',name:'Ipca Laboratories'},
    {companyid:'10686',name:'Vimta Labs'},
    {companyid:'8305',name:'Natco Pharma'},
    {companyid:'16325',name:'METROPOLIS'},
    {companyid:'40894',name:'Prabhat Dairy'},
    {companyid:'6833',name:'Vinati Organics'},
    {companyid:'10588',name:'Supreme Petrochem'},
    {companyid:'10519',name:'Ganesh Housing Corporation'},
    {companyid:'16827',name:'MSP Steel & Power'},
    {companyid:'34545',name:'Manaksia Aluminium Co'},
    {companyid:'6816',name:'Zydus Wellness'},
    {companyid:'9051',name:'Neuland Laboratories'},
    {companyid:'20366',name:'eClerx Services'},
    {companyid:'14027',name:'Atul'},
    {companyid:'12930',name:'AGC Networks'},
    {companyid:'13743',name:'GKW'},
    {companyid:'8352',name:'JSW Steel'},
    {companyid:'63225',name:'LALPATHLAB'},
    {companyid:'17605',name:'Aurionpro Solutions'},
    {companyid:'5136',name:'Aarvee Denims'},
    {companyid:'4155',name:'Cinevista'},
    {companyid:'41082',name:'NRB Industrial Bearings Ltd'},
    {companyid:'12692',name:'XPRO India'},]
}