export default {
    Data: [
        { mcsectorsymbol: 'in%3BSEN', name: 'SENSEX', mcsectorid: '4' },
{mcsectorsymbol:'in%3BNSX',name:'NIFTY50',mcsectorid:'9'},
// {mcsectorsymbol:'in%3Bccx',name:'NIFTYMidcap100',mcsectorid:'27'},
// {mcsectorsymbol:'in%3Bcnxs',name:'NIFTYSmallcap100',mcsectorid:'53'},
// {mcsectorsymbol:'in%3Bcjn',name:'NIFTYNEXT50',mcsectorid:'6'},
// {mcsectorsymbol:'in%3Bncx',name:'NIFTY500',mcsectorid:'7'},
// {mcsectorsymbol:'IN%3Baox',name:'BSEAuto',mcsectorid:'20'},
// {mcsectorsymbol:'in%3Bbip',name:'BSEIPO',mcsectorid:'33'},
// {mcsectorsymbol:'IN%3Bbkx',name:'BSEBANKEX',mcsectorid:'18'},
// {mcsectorsymbol:'IN%3BCDX',name:'BSEConsDurables',mcsectorid:'16'},
// {mcsectorsymbol:'IN%3BCGX',name:'BSECAPGOODS',mcsectorid:'13'},
// {mcsectorsymbol:'IN%3BMLX',name:'BSEMetal',mcsectorid:'21'},
// {mcsectorsymbol:'IN%3Bogx',name:'BSEOil&Gas',mcsectorid:'22'},
// {mcsectorsymbol:'in%3Bpbx',name:'BSEPSU',mcsectorid:'11'},
// {mcsectorsymbol:'in%3Brea',name:'BSEREALTY',mcsectorid:'29'},
// {mcsectorsymbol:'in%3Btkx',name:'BSETECk',mcsectorid:'10'},
// {mcsectorsymbol:'IN%3BNTL',name:'BSE100',mcsectorid:'1'},
// {mcsectorsymbol:'IN%3BSEI',name:'BSE200',mcsectorid:'2'},
// {mcsectorsymbol:'IN%3BBNX',name:'BSE500',mcsectorid:'12'},
// {mcsectorsymbol:'in%3Bbpo',name:'BSEPOWER',mcsectorid:'30'},
// {mcsectorsymbol:'in%3Bmfy',name:'NIFTYMIDCAP50',mcsectorid:'31'},
// {mcsectorsymbol:'in%3Bnnx',name:'NIFTY100',mcsectorid:'28'},
{mcsectorsymbol:'in%3Bnbx',name:'NIFTYBANK',mcsectorid:'23'},
{mcsectorsymbol:'in%3Bcnit',name:'NIFTYIT',mcsectorid:'19'},
{mcsectorsymbol:'in%3Bcrl',name:'NIFTYREALTY',mcsectorid:'34'},
{mcsectorsymbol:'in%3Bcfr',name:'NIFTYINFRA',mcsectorid:'35'},
{mcsectorsymbol:'in%3Bcgy',name:'NIFTYENERGY',mcsectorid:'38'},
{mcsectorsymbol:'in%3Bcfm',name:'NIFTYFMCG',mcsectorid:'39'},
{mcsectorsymbol:'in%3Bcxc',name:'NIFTYMNC',mcsectorid:'40'},
{mcsectorsymbol:'in%3Bcpr',name:'NIFTYPHARMA',mcsectorid:'41'},
{mcsectorsymbol:'in%3Bcps',name:'NIFTYPSE',mcsectorid:'42'},
{mcsectorsymbol:'in%3Bcuk',name:'NIFTYPSUBANK',mcsectorid:'43'},
{mcsectorsymbol:'in%3Bcrv',name:'NIFTYSERVSECTOR',mcsectorid:'44'},
{mcsectorsymbol:'in%3Bcnmx',name:'NIFTYMEDIA',mcsectorid:'50'},
{mcsectorsymbol:'in%3BCNXM',name:'NIFTYMETAL',mcsectorid:'51'},
{mcsectorsymbol:'in%3Bcnxa',name:'NIFTYAUTO',mcsectorid:'52'},
{mcsectorsymbol:'in%3BIDXN',name:'IndiaVIX',mcsectorid:'36'},
// {mcsectorsymbol:'mc%3Bfinsrv',name:'Nifty FinSrv25/50',mcsectorid:''},
// {mcsectorsymbol:'mc%3Balphalo',name:'NIFTY AlphaLowVol',mcsectorid:''},
//        { mcsectorsymbol: 'mc%3Bnmotm30', name: 'Nifty200 Momentum', mcsectorid: '' },
    ]
}